version: 2
updates:
  - open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    schedule:
      interval: "monthly"
    directory: "./"
    rebase-strategy: auto
